### PR TITLE
Optimized project structure, resources and did some refactorings

### PR DESCRIPTION
**Pull request by dannoe**
Quite a big change, if necessary I can split it up to multiple PRs

### CODE REVIEW

**Comment by dannoe** [comment]
There are some line ending errors in commit https://github.com/victor-rds/KeeTrayTOTP/pull/67/commits/9b1cb4f1614dcd4973aeef20a157a1bdbe73e580. I'm gonna fix them.

**Comment by dannoe** [comment]
Well, I found one thing out: Never ever doing such a big PR again. 👍

I'm gonna look at this tomorrow. Probably taking out the localization changes from this PR.

**Comment by dannoe** [comment]
@robinvanpoppel I removed the translation part and fixed all line ending errors. The PR should be ready for a review now.

**Comment by robinvanpoppel** [comment]
Thanks @dannoe : thanks again for your contribution!

I just checked quickly and this will improve maintenance of this plugin. I will probably take some time later this weekend to grab your branch and test a few things out as there is not a lot of test coverage right now. 

That's an area where I plan to do some more work to have more confidence in modernizing this codebase.

**Comment by dannoe** [comment]
@robinvanpoppel Thanks for the quick merge.

I am going to hold the translation stuff back, so we can focus more on refactorings.

**Pull request merged**
